recipes/devices/pi-kiosk.sh, scripts/components/install-kiosk-chromium.sh, scripts/image/chrootconfig.sh, scripts/makeimage.sh
This gets things rolling, but we need to seriously review all the chromium flags being set.
We should also consolidate with the ones set by @gvolt at [`touch_display`](https://github.com/volumio/volumio-plugins-sources/blob/master/touch_display/install.sh).
=> Improve kiosk package(s) installation

.gitignore, scripts/rootfs/configure.sh, scripts/rootfs/volumioconfig.sh, volumio/bin/welcome, volumio/lib/systemd/system/ip-changed@.target, volumio/lib/systemd/system/volumio-ipchange.service, volumio/lib/systemd/system/welcome.service
The welcome.service is now aware of IP address on network devices.
The additional volumio-ipchange service acts as a trigger for network interfaces whilst being restarted from static unit with descendants ip-changed@.target.
Any service depending on IP address change can be extended by making such service to be part of ip-monitor:
[Unit]
...
PartOf=ip-changed@eth0.target ip-changed@wlan0.target
Before=ip-changed@eth0.target ip-changed@wlan0.target
=> Qrcode on welcome screen with IP listenner

scripts/makeimage.sh
Sysvinit documentation is truncated when image is being built. Aftre booting, the dmesg reports litter as:
systemd[1]: memfd_create() called without MFD_EXEC or MFD_NOEXEC_SEAL set
systemd-sysv-generator[1220]: stat() failed on /etc/init.d/README, ignoring: No such file or directory
=> Cleaning legacy sysv-rc leftovers

recipes/devices/pi.sh
There is gcc mismatch between Bookworm and rpi-firmware and as such in chroot environment ld-linux.so.3 is complaining when using drop-ship to /usr directly
=> [raspberry] Work around gcc mismatch with CustomFirmware

recipes/base/x86.conf, scripts/initramfs/mkinitramfs-custom.sh
Bookworm uses unity /bin -> /usr/bin ; /sbin -> /usr/sbin folders since Debian 11. In theory should be no difference.
In init however we need to add fdisk utility at the device level.
Impact discussed here: https://github.com/volumio/volumio-os/issues/57
=> [x86] - Update device missing volbins

scripts/initramfs/README.md, scripts/initramfs/initv3, scripts/initramfs/scripts/volumio-functions
replace move_backup_gpt_table with maintain_device_partition
consumer - custom-functions at the device recipe level
=> [init] - Bookworm: manage device partiton table

scripts/initramfs/README.md
Just a few added lines, showing where to find the kernel boot parameters in an already built image
=> [initramfs] readme.md: how to modify kernel params for testing

recipes/devices/families/x86.sh, scripts/makeimage.sh
- add detection and reassembly of .tar.xz.part_* chunk sets for firmware and platform archives
- extract from reassembled .tar.xz if chunks present; fallback to full archive if available
- suppress hard failure if firmware archive is missing; log warning instead
- suppress hard failure if platform archive is missing; log warning instead
- preserves compatibility with devices that do not require firmware or platform overlays
- ensures compatibility with GitHub’s file size limits without breaking build logic
=> make firmware and platform archives optional; add support for chunked input

recipes/devices/families/x86.sh, scripts/makeimage.sh
- allow optional DEVICEREPO_BRANCH to override default branch
- fallback to default clone behavior if not specified
- supports use of stable or feature branches per device or kernel line
=> [x86] - Add support for platform repo branch selection

recipes/devices/families/x86.sh, volumio/lib/systemd/system/volumio_rfkill_runtime.path, volumio/lib/systemd/system/volumio_rfkill_runtime.service, volumio/lib/systemd/system/volumio_rfkill_unblock.service
This PR resolves a known OTA update failure caused by insufficient space in the partition layout and introduces runtime handling for `rfkill` soft-block issues affecting Wi-Fi and Bluetooth.
* Align partitions to **1 MiB boundaries** for optimal SD/USB/SSD performance
* Use **GPT** with **UUID-based boot references** for modern bootloader compatibility
* Increase total image size to **4865 MiB** to:
* Ensure headroom for OTA delta updates
* Accommodate squashfs workspace and overlay expansion
* Support upcoming features like on-screen keyboard and sensor automation
* Add runtime unblock logic using **systemd .path/.service** units:
* Watches `/dev/rfkill` and unblocks interfaces on detection
* Implements quiet, non-interactive handling to fix devices soft-blocked by firmware or boot …
=> Fix OTA failure with aligned partitions and add runtime rfkill unblock service

HARDWARE_SUPPORT_REQUEST.md
This PR adds a structured Markdown template (`HARDWARE_SUPPORT_REQUEST_TEMPLATE.md`) to standardize community and issue-based hardware support requests.
The template requires users to:
- Clearly identify hardware via lsusb/lspci
- Provide vendor, revision, and technical documentation
- Include links to datasheets, product pages, or source repositories
- Describe the intended use within Volumio OS
- Acknowledge that incomplete submissions will be rejected
Also includes a "bad example" section to illustrate what will not be accepted.
This template may be linked from both GitHub issues and the Volumio community forum.
=> Add hardware support request template for Bookworm-based Volumio OS

recipes/devices/pi.sh
This PR adds the finalized `firmware-volumio.tar.gz` firmware bundle for Volumio on Raspberry Pi.
Contents include:
- Blobs from linux-firmware.git (e.g., mediatek/, rtlwifi/, rtl_nic/)
- Manually injected Realtek and Ralink firmware:
- rtl_bt/rtl8723cs_cg_config.bin
- rtl_bt/rtl8723cs_cg_fw.bin
- rtl_bt/rtl8723ds_config.bin
- rtl_bt/rtl8723ds_fw.bin
- rt3070.bin
=> Add firmware-volumio.tar.gz for Raspberry Pi

scripts/rootfs/volumioconfig.sh
- Added Wants= and After= for volumio_rfkill_unblock.service to hostapd.service
- Maintains existing build-time customization style using sed
- Ensures Wi-Fi soft block is cleared before access point initialization
- Prevents hostapd startup failure due to rfkill state on early boot
=> Ensure rfkill unblock before hostapd startup in image build

recipes/base/VolumioBase.conf, scripts/components/install-kiosk-legacy-chromium.sh
This PR replaces APT-based Chromium installation with a version-specific, architecture-aware approach using GitHub-hosted .deb packages. It resolves issues caused by package version mismatches and missing dependencies on Debian 12.
Changes include:
- Dynamic selection of chromium, chromium-common, and chromium-l10n based on detected architecture
- Download to and cleanup from a temporary directory
- Compatibility maintained with Debian 12 library versions
- Prepares the kiosk script for consistent behavior across devices
=> [kiosk mode] - Use GitHub-hosted Chromium packages by architecture for kiosk setup

volumio/bin/firststart.sh
This PR disables and masks alsa-restore.service and alsa-state.service via systemd to ensure they do not interfere with Volumio's custom audio configuration. This change is necessary for maintaining a controlled, bit-perfect audio environment.
=>  Disable and Mask systemd ALSA Services

scripts/rootfs/configure.sh, volumio/etc/systemd/system/nmbd.service.d/override.conf, volumio/etc/systemd/system/winbind.service.d/override.conf
This PR introduces systemd override files to ensure correct and efficient startup sequencing for Samba-related services:
* `winbind.service` now explicitly starts *after* `smbd.service` and `network-online.target`
* `nmbd.service` starts *after* `winbind.service`
These changes prevent premature invocation of network-dependent components and help reduce early boot-time blocking caused by DNS, DHCP, or delayed link-up. Overrides are placed in:
```
/etc/systemd/system/winbind.service.d/override.conf
/etc/systemd/system/nmbd.service.d/override.conf
```
This improves reliability across both wired and wireless Volumio deployments.
=>  Optimize Samba Systemd Startup Order with Override Units

volumio/etc/systemd/system/volumio.service.d/override.conf
This PR adds a systemd override for `volumio.service` to enforce proper startup order by requiring:
```
After=alsa-restore.service
Requires=alsa-restore.service
```
This ensures the Volumio backend does not start before the ALSA state is restored and all sound cards are initialized. It prevents race conditions with mixer access and guarantees a stable audio environment at boot.
The override is installed at:
```
/etc/systemd/system/volumio.service.d/override.conf
```
=>  Ensure Volumio Service Starts After ALSA Restore

scripts/rootfs/volumioconfig.sh
- Masked /etc/udev/rules.d/10-local.rules by symlinking to /dev/null
- Original rule runs 'hciconfig hci0 up' too early via udev, causing exit code 1
- BlueZ already handles bring-up via AutoEnable=true in main.conf
- Prevents race condition and redundant interface activation on boot
=> fix - bluetooth: mask upstream udev rule forcing premature hci0 bring-up

volumio/etc/udev/rules.d/99-restart-thd-on-hid.rules
- Replaced ATTRS{phys} match with ENV{ID_BUS}=="bluetooth" for broader compatibility
- Ensures triggerhappy is restarted when new Bluetooth input devices are added via uhid
- Resolves issue where BlueZ HID devices (e.g., remotes, keyboards) were not functional until manual service restart
=> Update udev rule to reliably restart triggerhappy on Bluetooth HID device connection

scripts/rootfs/volumioconfig.sh, volumio/bin/th-udev-rebind.sh, volumio/lib/systemd/system/th-udev-rebind.service, volumio/lib/systemd/system/triggerhappy.service
triggerhappy: switch to service-only mode with explicit rebind
- Updated triggerhappy.service to use --socket explicitly with --deviceglob
- Disabled triggerhappy.socket to avoid systemd socket activation conflicts
- Ensured reliable /bin/th-udev-rebind.sh operation using --add and --socket
- Updated volumioconfig.sh:
- Masked triggerhappy.socket using override.conf and symlink suppression
- Fixes segmentation fault and "Transport endpoint is not connected" errors
- Required for consistent remote input functionality (e.g., Bluetooth keyboards)
=> triggerhappy: switch to service-only mode with explicit rebind

recipes/devices/pi.sh
This PR resolves a critical regression affecting Volumio Bookworm BETA builds using kernel 6.12.34 on Raspberry Pi.
Problem:
- Stray module directories like 6.12.34+rpt-rpi-2712, +rpt-rpi-v6, etc., were being created but not populated, causing depmod warnings and in some cases breaking the boot process, especially on Raspberry Pi 5.
Fix:
- Explicitly remove any /lib/modules/*+rpt-rpi-* directories prior to depmod and initramfs generation.
- Confirmed working on Pi5dev with clean boot.
This regression was introduced in the past week and did not affect earlier builds such as 4.017.
=> Fix boot issues on Pi by removing unintended +rpt-rpi-* kernel module directories

recipes/devices/families/x86.sh
=> [x86.sh] A "slow" x86 confguration may need more time to initialise USB
