- scripts/image/chrootconfig.sh
- scripts/rootfs/configure.sh
- volumio/framebuffer/systemd/system/plymouth-halt.service
- volumio/framebuffer/systemd/system/plymouth-kexec.service
- volumio/framebuffer/systemd/system/plymouth-poweroff.service
- volumio/framebuffer/systemd/system/plymouth-reboot.service
- volumio/framebuffer/systemd/system/plymouth-start.service
- volumio/framebuffer/systemd/system/plymouth-switch-root-initramfs.service
Cherry-picked from #3 ([foonerd/volumio-os](https://github.com/foonerd/volumio-os/))
> Plymouth improvements for Bookworm

- recipes/base/arm.conf
- recipes/configurations/config.sh
- recipes/devices/pi.sh
- scripts/initramfs/mkinitramfs-custom.sh
Consider this a WIP base.
Consolidated @foonerd's tweaks as well. 
We still have a lot of bits and pieces that aren't in line with Debian Bookworm, but this boots and plays :-)
> Bookworm on pi

- recipes/devices/bananapim1.sh
- recipes/devices/bananapipro.sh
- recipes/devices/cm4.sh
- recipes/devices/families/nanopi-armbian_h3.sh
- recipes/devices/families/nanopi-armbian_h5.sh
- recipes/devices/families/nanopi-armbian_rk3328.sh
- recipes/devices/families/orangepi_h3.sh
- recipes/devices/mp0.sh
- recipes/devices/nanopineo2-a.sh
- recipes/devices/nanopineo2.sh
- recipes/devices/nanopineo3.sh
- recipes/devices/pi.sh
- scripts/makeimage.sh
Add `INIT_UUID_TYPE` for devices with special case UUIDs.
> Consolidate initramfs scripts handling into `makeimage`

- scripts/makeimage.sh
with gzip
```
[ o.k. ] Squash filesystem created  [ 577M ]
[ o.k. ] Image pi.img Created  [ 10:27 min ]
[ o.k. ] Image pi.zip Created [ 656M ]
```
with zstd
```
[ o.k. ] Squash filesystem created  [ 538M ]
[ o.k. ] Image pi.img Created  [ 10:43 min ]
[ o.k. ] Image pi.zip Created [ 619M ]
```
> Switch squashfs compression to zstd to save space

- installer/board-config/pi/mkinstall_config.sh
- recipes/devices/pi.sh
Disabling modules=list with this commit.
> Minimal set of modules for init use on pi recipe

- recipes/devices/pi.sh
- scripts/makeimage.sh
> Switch squashfs compression back to gzip

- recipes/devices/pi.sh
Fix for Issue: https://github.com/volumio/volumio-os/issues/22
> Audio routing over HDMI0 or HDMI1 pi 5

- recipes/configurations/config.sh
Volumio's backend is using latest kernel 6.6 changes.
> Restore backend branch to master

- scripts/rootfs/configure.sh
- scripts/rootfs/volumioconfig.sh
- volumio/bin/volumio_rfkill_unblock.sh
- volumio/lib/systemd/system/volumio_rfkill_unblock.service
Fix for rfkill forcing to use nmcli https://github.com/volumio/volumio-os/issues/27
> [generic] - Manage nl80211 modules blocking state service

- recipes/devices/pi.sh
The --strip-components behaviour has changed and need to be researched
> [raspberry] - Enable CustomFirmware

- recipes/devices/cm4.sh
Temporary fix for https://github.com/volumio/volumio-os/issues/45
> [cm4] - mesa libs unmet dependencies

- recipes/devices/pi.sh
Temporary fix for issue https://github.com/volumio/volumio-os/issues/45
> [pi] - mesa libs unmet dependencies

- recipes/devices/cm4.sh
- recipes/devices/pi.sh
CM4 is ahead of pi branch - aligning with master
> Aliging from master

- recipes/base/VolumioBase.conf
alsa-ucm-conf
bluez-alsa-utils
> [generic] Alsa dependencies

- recipes/base/x86.conf
- scripts/initramfs/mkinitramfs-custom.sh
Test init shows fdisk utility present.
> [x86] - Update device missing volbins

- scripts/initramfs/README.md
- scripts/initramfs/initv3
- scripts/initramfs/scripts/volumio-functions
replace move_backup_gpt_table with maintain_device_partition
consumer - custom-functions at the device recipe level
> [init] - manage device partiton table

- recipes/devices/x86_amd64.sh
- scripts/initramfs/custom/x86/custom-functions
For now, I need to intercept GPT partition state from stdio to /tmp/parted sentinel
> [x86] - Manage GPT partition on disk change

- scripts/rootfs/configure.sh
- scripts/rootfs/volumioconfig.sh
- volumio/bin/manage_user_groups.sh
- volumio/bin/users_to_groups.sh
- volumio/bin/volumio_fs_protection.sh
- volumio/etc/groups-config.conf
- volumio/lib/systemd/system/volumio_fs_protection.service
- volumio/lib/systemd/system/volumio_groups_manager.service
Resolving issue: https://github.com/volumio/volumio-os/issues/75
> Users and protection management service

- scripts/rootfs/volumioconfig.sh
Change - important!
alias snapclient="/usr/bin/snapclient"
alias snapserver="/usr/bin/snapserver"
> [system] - update unity aliases

- volumio/plymouth/themes/volumio-player/volumio-player.script
This update refines the Volumio Plymouth theme script to improve readability across all screen sizes:
- Dynamically adjusts message positioning below the animation
- Scales font size for small displays (<240px)
- Auto-reduces scroll lines if vertical space is limited
- Applies fading opacity to older log lines for visual clarity
Fully backward compatible with existing assets.
> [plymouth] - Enhance Volumio boot splash: responsive message layout, font scaling, and line fading

- volumio/plymouth/themes/volumio-player/volumio-player.script
This update refines the Volumio Plymouth theme script to improve readability across all screen sizes:
- Dynamically adjusts message positioning below the animation
- Scales font size for small displays (<240px)
- Auto-reduces scroll lines if vertical space is limited
- Applies fading opacity to older log lines for visual clarity
Fully backward compatible with existing assets.
> Enhance Volumio boot splash: responsive message layout, font scaling, and line fading

- scripts/rootfs/configure.sh
- scripts/rootfs/volumioconfig.sh
- volumio/bin/fix-alpha-hosts.sh
- volumio/etc/systemd/fix-alpha-hosts.path
- volumio/etc/systemd/fix-alpha-hosts.service
> Add systemd watcher to restore /etc/hosts and ensure test sentinels after setup wizard

- volumio/etc/udev/rules.d/09-hemdevices.rules
Origin - from [volumio3-os PR](https://github.com/volumio/volumio3-os/pull/254)
> [generic] - add hem vendor udev rule

- recipes/devices/families/x86.sh
[[x86] Corrected acpi handling](https://github.com/volumio/volumio-os/commit/69af5b61b7edb9072c2eef41c8a6adb6fe6fabcc)
> [x86] Corrected acpi handling

- recipes/devices/cm4.sh
- recipes/devices/pi.sh
- udev rules
- alsa resore systmd service override
> [pi] - Service rules adjustment

- recipes/base/VolumioBase.conf
- scripts/components/install-kiosk-chromium.sh
- scripts/components/install-kiosk-legacy-chromium.sh
- On-screen keyboard
- Lock-in chromium version
> [x86_amd64] - Kiosk service improvements

- recipes/base/arm.conf
- libertas
- mediatek
- marvell-prestera
> [pi] - Additional firmware referenced by Raspbian

- recipes/devices/cm4.sh
This PR resolves a critical regression affecting Volumio Bookworm BETA builds using kernel 6.12.34 on Raspberry Pi.
Problem:
- Stray module directories like 6.12.34+rpt-rpi-2712, +rpt-rpi-v6, etc., were being created but not populated, causing depmod warnings and in some cases breaking the boot process, especially on Raspberry Pi 5.
Fix:
- Explicitly remove any /lib/modules/*+rpt-rpi-* directories prior to depmod and initramfs generation.
- Confirmed working on Pi5dev with clean boot.
> [cm4] - sync up with recent upstream kernel changes

- recipes/base/VolumioBase.conf
- recipes/configurations/config.sh
> Update mpd and bluez

- scripts/components/install-kiosk-chromium.sh
- scripts/components/install-kiosk-vivaldi.sh
Remove chromium version pinning
> kiosk - switch to onscreen keyboard v3
